### PR TITLE
Fix incorrect emoji text.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by notriddle** [comment]
I think :not_good: is the only one. I was sure Github had one for that, but maybe that was just Slack...

**Comment by frewsxcv** [comment]
Could also just do the literal unicode character, instead of this `:foo:` funny business.

**Comment by notriddle** [comment]
I'm not sure if all of them have applicable unicode, but where they do, Github translates for us anyway (I never see `:+1` in emails).

**Comment by frewsxcv** [comment]
In any case:

screen shot 2016-08-22 at 5 54 15 pm

**Comment by notriddle** [comment]
@aelita-mergebot r+

**Pull request merged**
