### PR TITLE
Improve the UI look and feel

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Comment by notriddle** [comment]
r? @emoon 

These changes are actually deployed to aelitabot.xyz already, so that you can see how they look. I'm asking you because you seem familiar enough with HTML and JS to critique it. If @frewsxcv, @nox, or @hauleth want to look, you can, too.

**Comment by emoon** [comment]
Funny thing I i started to learn HTML/CSS/JS *this* week :) So I'm not really that familiar with it to have a strong opinion (yet!)

**Comment by notriddle** [comment]
Woops, got you and hauleth mixed up (looked at his GitHub page and saw the SCSS framework thing). r? @hauleth

**Comment by notriddle** [comment]
@aelita-mergebot r+

**Comment by notriddle** [comment]
@aelita-mergebot r+

**Pull request merged**
