### PR TITLE
Add multi-CI support

### LINKED ISSUE #51: Allow github status CI to use more than one status
This would allow, for example, repos that use both AppVeyor and Travis CI to let Aelita wait on both.

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #51

### CODE REVIEW

**Comment by notriddle** [comment]
@aelita-mergebot r+

**Comment by notriddle** [comment]
@aelita-mergebot r+

**Comment by notriddle** [comment]
@aelita-mergebot r+

**Comment by alexcrichton** [comment]
Nice! Could the example configs also be updated with syntax of how to configure this?

**Comment by notriddle** [comment]
Sure. #123

**Pull request merged**
